"""add_plan_completion_tracking

Revision ID: 01cc5a0f7e47
Revises: 15427ad02ab2
Create Date: 2025-10-09 10:44:36.015556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cc5a0f7e47'
down_revision: Union[str, None] = '15427ad02ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
