"""add_exercises_to_workout_sessions

Revision ID: 15427ad02ab2
Revises: 89dae53f360e
Create Date: 2025-10-08 11:12:48.975839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15427ad02ab2'
down_revision: Union[str, None] = '89dae53f360e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('exercises', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'exercises')
    # ### end Alembic commands ###
