"""add_start_date_to_saved_plans

Revision ID: 89dae53f360e
Revises: fdf3f3f61a89
Create Date: 2025-10-07 17:47:59.157180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89dae53f360e'
down_revision: Union[str, None] = 'fdf3f3f61a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_plans', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_plans', 'start_date')
    # ### end Alembic commands ###
