"""add_calories_burned_to_workout_sessions

Revision ID: 8e506b62392c
Revises: 01cc5a0f7e47
Create Date: 2025-10-13 10:03:54.645540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e506b62392c'
down_revision: Union[str, None] = '01cc5a0f7e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('calories_burned', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'calories_burned')
    # ### end Alembic commands ###
