"""Add experience level and plan categorization

Revision ID: a08abcac0f67
Revises: 
Create Date: 2025-09-26 15:41:47.180172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08abcac0f67'
down_revision: Union[str, None] = '12066cfaf4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add experience_level to users table
    op.add_column('users', sa.Column('experience_level', sa.String(length=255), nullable=True))
    
    # Add level and duration_days to workouts table
    op.add_column('workouts', sa.Column('level', sa.String(length=50), nullable=True))
    op.add_column('workouts', sa.Column('duration_days', sa.Integer(), nullable=True))
    
    # Make owner_id nullable for workouts (if table exists)
    try:
        op.alter_column('workouts', 'owner_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    except Exception:
        # Table might not exist yet, skip this change
        pass
    
    # Make owner_id nullable for exercises (if table exists)
    try:
        op.alter_column('exercises', 'owner_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    except Exception:
        # Table might not exist yet, skip this change
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('workouts', 'duration_days')
    op.drop_column('workouts', 'level')
    op.drop_column('users', 'experience_level')
    op.alter_column('exercises', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
