"""Add SavedPlan table

Revision ID: fdf3f3f61a89
Revises: a08abcac0f67
Create Date: 2025-09-26 16:02:31.856328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf3f3f61a89'
down_revision: Union[str, None] = 'a08abcac0f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_plans_id'), 'saved_plans', ['id'], unique=False)
    op.create_index(op.f('ix_saved_plans_user_id'), 'saved_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_plans_workout_id'), 'saved_plans', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_plans_workout_id'), table_name='saved_plans')
    op.drop_index(op.f('ix_saved_plans_user_id'), table_name='saved_plans')
    op.drop_index(op.f('ix_saved_plans_id'), table_name='saved_plans')
    op.drop_table('saved_plans')
    # ### end Alembic commands ###
